export enum CaseStatus {
  NEW = 'NEW',
  WAITING_FOR_USER = 'WAITING_FOR_USER',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  CANCELED = 'CANCELED',
}
