/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionTimeoutRouteImport } from './routes/session-timeout'
import { Route as CoreRouteRouteImport } from './routes/_core/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoreUsersIndexRouteImport } from './routes/_core/users/index'
import { Route as CoreRolesIndexRouteImport } from './routes/_core/roles/index'
import { Route as CorePermissionsIndexRouteImport } from './routes/_core/permissions/index'
import { Route as CoreDashboardIndexRouteImport } from './routes/_core/dashboard/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as CoreUsersCreateRouteImport } from './routes/_core/users/create'
import { Route as CoreUsersUserIdRouteImport } from './routes/_core/users/$userId'
import { Route as CoreSettingsLdapIndexRouteImport } from './routes/_core/settings/ldap/index'

const SessionTimeoutRoute = SessionTimeoutRouteImport.update({
  id: '/session-timeout',
  path: '/session-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRouteRoute = CoreRouteRouteImport.update({
  id: '/_core',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreUsersIndexRoute = CoreUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRolesIndexRoute = CoreRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CorePermissionsIndexRoute = CorePermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDashboardIndexRoute = CoreDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CoreUsersCreateRoute = CoreUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUsersUserIdRoute = CoreUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreSettingsLdapIndexRoute = CoreSettingsLdapIndexRouteImport.update({
  id: '/settings/ldap/',
  path: '/settings/ldap/',
  getParentRoute: () => CoreRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/users/$userId': typeof CoreUsersUserIdRoute
  '/users/create': typeof CoreUsersCreateRoute
  '/login/': typeof AuthLoginIndexRoute
  '/dashboard/': typeof CoreDashboardIndexRoute
  '/permissions/': typeof CorePermissionsIndexRoute
  '/roles/': typeof CoreRolesIndexRoute
  '/users/': typeof CoreUsersIndexRoute
  '/settings/ldap/': typeof CoreSettingsLdapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/users/$userId': typeof CoreUsersUserIdRoute
  '/users/create': typeof CoreUsersCreateRoute
  '/login': typeof AuthLoginIndexRoute
  '/dashboard': typeof CoreDashboardIndexRoute
  '/permissions': typeof CorePermissionsIndexRoute
  '/roles': typeof CoreRolesIndexRoute
  '/users': typeof CoreUsersIndexRoute
  '/settings/ldap': typeof CoreSettingsLdapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_core': typeof CoreRouteRouteWithChildren
  '/session-timeout': typeof SessionTimeoutRoute
  '/_core/users/$userId': typeof CoreUsersUserIdRoute
  '/_core/users/create': typeof CoreUsersCreateRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_core/dashboard/': typeof CoreDashboardIndexRoute
  '/_core/permissions/': typeof CorePermissionsIndexRoute
  '/_core/roles/': typeof CoreRolesIndexRoute
  '/_core/users/': typeof CoreUsersIndexRoute
  '/_core/settings/ldap/': typeof CoreSettingsLdapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session-timeout'
    | '/users/$userId'
    | '/users/create'
    | '/login/'
    | '/dashboard/'
    | '/permissions/'
    | '/roles/'
    | '/users/'
    | '/settings/ldap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/session-timeout'
    | '/users/$userId'
    | '/users/create'
    | '/login'
    | '/dashboard'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/settings/ldap'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_core'
    | '/session-timeout'
    | '/_core/users/$userId'
    | '/_core/users/create'
    | '/_auth/login/'
    | '/_core/dashboard/'
    | '/_core/permissions/'
    | '/_core/roles/'
    | '/_core/users/'
    | '/_core/settings/ldap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CoreRouteRoute: typeof CoreRouteRouteWithChildren
  SessionTimeoutRoute: typeof SessionTimeoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session-timeout': {
      id: '/session-timeout'
      path: '/session-timeout'
      fullPath: '/session-timeout'
      preLoaderRoute: typeof SessionTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core': {
      id: '/_core'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core/users/': {
      id: '/_core/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof CoreUsersIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/roles/': {
      id: '/_core/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof CoreRolesIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/permissions/': {
      id: '/_core/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof CorePermissionsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/dashboard/': {
      id: '/_core/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof CoreDashboardIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_core/users/create': {
      id: '/_core/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof CoreUsersCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/users/$userId': {
      id: '/_core/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof CoreUsersUserIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/settings/ldap/': {
      id: '/_core/settings/ldap/'
      path: '/settings/ldap'
      fullPath: '/settings/ldap/'
      preLoaderRoute: typeof CoreSettingsLdapIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CoreRouteRouteChildren {
  CoreUsersUserIdRoute: typeof CoreUsersUserIdRoute
  CoreUsersCreateRoute: typeof CoreUsersCreateRoute
  CoreDashboardIndexRoute: typeof CoreDashboardIndexRoute
  CorePermissionsIndexRoute: typeof CorePermissionsIndexRoute
  CoreRolesIndexRoute: typeof CoreRolesIndexRoute
  CoreUsersIndexRoute: typeof CoreUsersIndexRoute
  CoreSettingsLdapIndexRoute: typeof CoreSettingsLdapIndexRoute
}

const CoreRouteRouteChildren: CoreRouteRouteChildren = {
  CoreUsersUserIdRoute: CoreUsersUserIdRoute,
  CoreUsersCreateRoute: CoreUsersCreateRoute,
  CoreDashboardIndexRoute: CoreDashboardIndexRoute,
  CorePermissionsIndexRoute: CorePermissionsIndexRoute,
  CoreRolesIndexRoute: CoreRolesIndexRoute,
  CoreUsersIndexRoute: CoreUsersIndexRoute,
  CoreSettingsLdapIndexRoute: CoreSettingsLdapIndexRoute,
}

const CoreRouteRouteWithChildren = CoreRouteRoute._addFileChildren(
  CoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CoreRouteRoute: CoreRouteRouteWithChildren,
  SessionTimeoutRoute: SessionTimeoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
