/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionTimeoutRouteImport } from './routes/session-timeout'
import { Route as EsmRouteRouteImport } from './routes/_esm/route'
import { Route as CoreRouteRouteImport } from './routes/_core/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsmCasesIndexRouteImport } from './routes/_esm/cases/index'
import { Route as CoreUsersIndexRouteImport } from './routes/_core/users/index'
import { Route as CoreSlaIndexRouteImport } from './routes/_core/sla/index'
import { Route as CoreSettingsIndexRouteImport } from './routes/_core/settings/index'
import { Route as CoreRolesIndexRouteImport } from './routes/_core/roles/index'
import { Route as CorePermissionsIndexRouteImport } from './routes/_core/permissions/index'
import { Route as CoreGroupsIndexRouteImport } from './routes/_core/groups/index'
import { Route as CoreDepartmentsIndexRouteImport } from './routes/_core/departments/index'
import { Route as CoreDashboardIndexRouteImport } from './routes/_core/dashboard/index'
import { Route as CoreCategoriesIndexRouteImport } from './routes/_core/categories/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as EsmCasesCreateRouteImport } from './routes/_esm/cases/create'
import { Route as CoreUsersCreateRouteImport } from './routes/_core/users/create'
import { Route as CoreUsersUserIdRouteImport } from './routes/_core/users/$userId'
import { Route as CoreSlaCreateRouteImport } from './routes/_core/sla/create'
import { Route as CoreSlaSlaIdRouteImport } from './routes/_core/sla/$slaId'
import { Route as CoreRolesCreateRouteImport } from './routes/_core/roles/create'
import { Route as CoreRolesRoleIdRouteImport } from './routes/_core/roles/$roleId'
import { Route as CoreGroupsCreateRouteImport } from './routes/_core/groups/create'
import { Route as CoreGroupsGroupIdRouteImport } from './routes/_core/groups/$groupId'
import { Route as CoreDepartmentsCreateRouteImport } from './routes/_core/departments/create'
import { Route as CoreDepartmentsDepartmentIdRouteImport } from './routes/_core/departments/$departmentId'
import { Route as CoreCategoriesCreateRouteImport } from './routes/_core/categories/create'
import { Route as CoreCategoriesCategoryIdRouteImport } from './routes/_core/categories/$categoryId'
import { Route as EsmCasesCaseIdIndexRouteImport } from './routes/_esm/cases/$caseId/index'
import { Route as CoreSettingsLdapIndexRouteImport } from './routes/_core/settings/ldap/index'
import { Route as EsmCasesCaseIdEditIndexRouteImport } from './routes/_esm/cases/$caseId/edit/index'

const SessionTimeoutRoute = SessionTimeoutRouteImport.update({
  id: '/session-timeout',
  path: '/session-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const EsmRouteRoute = EsmRouteRouteImport.update({
  id: '/_esm',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRouteRoute = CoreRouteRouteImport.update({
  id: '/_core',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsmCasesIndexRoute = EsmCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => EsmRouteRoute,
} as any)
const CoreUsersIndexRoute = CoreUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreSlaIndexRoute = CoreSlaIndexRouteImport.update({
  id: '/sla/',
  path: '/sla/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreSettingsIndexRoute = CoreSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRolesIndexRoute = CoreRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CorePermissionsIndexRoute = CorePermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreGroupsIndexRoute = CoreGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDepartmentsIndexRoute = CoreDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDashboardIndexRoute = CoreDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreCategoriesIndexRoute = CoreCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const EsmCasesCreateRoute = EsmCasesCreateRouteImport.update({
  id: '/cases/create',
  path: '/cases/create',
  getParentRoute: () => EsmRouteRoute,
} as any)
const CoreUsersCreateRoute = CoreUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUsersUserIdRoute = CoreUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreSlaCreateRoute = CoreSlaCreateRouteImport.update({
  id: '/sla/create',
  path: '/sla/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreSlaSlaIdRoute = CoreSlaSlaIdRouteImport.update({
  id: '/sla/$slaId',
  path: '/sla/$slaId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRolesCreateRoute = CoreRolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRolesRoleIdRoute = CoreRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreGroupsCreateRoute = CoreGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreGroupsGroupIdRoute = CoreGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDepartmentsCreateRoute = CoreDepartmentsCreateRouteImport.update({
  id: '/departments/create',
  path: '/departments/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDepartmentsDepartmentIdRoute =
  CoreDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => CoreRouteRoute,
  } as any)
const CoreCategoriesCreateRoute = CoreCategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreCategoriesCategoryIdRoute =
  CoreCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => CoreRouteRoute,
  } as any)
const EsmCasesCaseIdIndexRoute = EsmCasesCaseIdIndexRouteImport.update({
  id: '/cases/$caseId/',
  path: '/cases/$caseId/',
  getParentRoute: () => EsmRouteRoute,
} as any)
const CoreSettingsLdapIndexRoute = CoreSettingsLdapIndexRouteImport.update({
  id: '/settings/ldap/',
  path: '/settings/ldap/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const EsmCasesCaseIdEditIndexRoute = EsmCasesCaseIdEditIndexRouteImport.update({
  id: '/cases/$caseId/edit/',
  path: '/cases/$caseId/edit/',
  getParentRoute: () => EsmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/categories/$categoryId': typeof CoreCategoriesCategoryIdRoute
  '/categories/create': typeof CoreCategoriesCreateRoute
  '/departments/$departmentId': typeof CoreDepartmentsDepartmentIdRoute
  '/departments/create': typeof CoreDepartmentsCreateRoute
  '/groups/$groupId': typeof CoreGroupsGroupIdRoute
  '/groups/create': typeof CoreGroupsCreateRoute
  '/roles/$roleId': typeof CoreRolesRoleIdRoute
  '/roles/create': typeof CoreRolesCreateRoute
  '/sla/$slaId': typeof CoreSlaSlaIdRoute
  '/sla/create': typeof CoreSlaCreateRoute
  '/users/$userId': typeof CoreUsersUserIdRoute
  '/users/create': typeof CoreUsersCreateRoute
  '/cases/create': typeof EsmCasesCreateRoute
  '/login/': typeof AuthLoginIndexRoute
  '/categories/': typeof CoreCategoriesIndexRoute
  '/dashboard/': typeof CoreDashboardIndexRoute
  '/departments/': typeof CoreDepartmentsIndexRoute
  '/groups/': typeof CoreGroupsIndexRoute
  '/permissions/': typeof CorePermissionsIndexRoute
  '/roles/': typeof CoreRolesIndexRoute
  '/settings/': typeof CoreSettingsIndexRoute
  '/sla/': typeof CoreSlaIndexRoute
  '/users/': typeof CoreUsersIndexRoute
  '/cases/': typeof EsmCasesIndexRoute
  '/settings/ldap/': typeof CoreSettingsLdapIndexRoute
  '/cases/$caseId/': typeof EsmCasesCaseIdIndexRoute
  '/cases/$caseId/edit/': typeof EsmCasesCaseIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/categories/$categoryId': typeof CoreCategoriesCategoryIdRoute
  '/categories/create': typeof CoreCategoriesCreateRoute
  '/departments/$departmentId': typeof CoreDepartmentsDepartmentIdRoute
  '/departments/create': typeof CoreDepartmentsCreateRoute
  '/groups/$groupId': typeof CoreGroupsGroupIdRoute
  '/groups/create': typeof CoreGroupsCreateRoute
  '/roles/$roleId': typeof CoreRolesRoleIdRoute
  '/roles/create': typeof CoreRolesCreateRoute
  '/sla/$slaId': typeof CoreSlaSlaIdRoute
  '/sla/create': typeof CoreSlaCreateRoute
  '/users/$userId': typeof CoreUsersUserIdRoute
  '/users/create': typeof CoreUsersCreateRoute
  '/cases/create': typeof EsmCasesCreateRoute
  '/login': typeof AuthLoginIndexRoute
  '/categories': typeof CoreCategoriesIndexRoute
  '/dashboard': typeof CoreDashboardIndexRoute
  '/departments': typeof CoreDepartmentsIndexRoute
  '/groups': typeof CoreGroupsIndexRoute
  '/permissions': typeof CorePermissionsIndexRoute
  '/roles': typeof CoreRolesIndexRoute
  '/settings': typeof CoreSettingsIndexRoute
  '/sla': typeof CoreSlaIndexRoute
  '/users': typeof CoreUsersIndexRoute
  '/cases': typeof EsmCasesIndexRoute
  '/settings/ldap': typeof CoreSettingsLdapIndexRoute
  '/cases/$caseId': typeof EsmCasesCaseIdIndexRoute
  '/cases/$caseId/edit': typeof EsmCasesCaseIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_core': typeof CoreRouteRouteWithChildren
  '/_esm': typeof EsmRouteRouteWithChildren
  '/session-timeout': typeof SessionTimeoutRoute
  '/_core/categories/$categoryId': typeof CoreCategoriesCategoryIdRoute
  '/_core/categories/create': typeof CoreCategoriesCreateRoute
  '/_core/departments/$departmentId': typeof CoreDepartmentsDepartmentIdRoute
  '/_core/departments/create': typeof CoreDepartmentsCreateRoute
  '/_core/groups/$groupId': typeof CoreGroupsGroupIdRoute
  '/_core/groups/create': typeof CoreGroupsCreateRoute
  '/_core/roles/$roleId': typeof CoreRolesRoleIdRoute
  '/_core/roles/create': typeof CoreRolesCreateRoute
  '/_core/sla/$slaId': typeof CoreSlaSlaIdRoute
  '/_core/sla/create': typeof CoreSlaCreateRoute
  '/_core/users/$userId': typeof CoreUsersUserIdRoute
  '/_core/users/create': typeof CoreUsersCreateRoute
  '/_esm/cases/create': typeof EsmCasesCreateRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_core/categories/': typeof CoreCategoriesIndexRoute
  '/_core/dashboard/': typeof CoreDashboardIndexRoute
  '/_core/departments/': typeof CoreDepartmentsIndexRoute
  '/_core/groups/': typeof CoreGroupsIndexRoute
  '/_core/permissions/': typeof CorePermissionsIndexRoute
  '/_core/roles/': typeof CoreRolesIndexRoute
  '/_core/settings/': typeof CoreSettingsIndexRoute
  '/_core/sla/': typeof CoreSlaIndexRoute
  '/_core/users/': typeof CoreUsersIndexRoute
  '/_esm/cases/': typeof EsmCasesIndexRoute
  '/_core/settings/ldap/': typeof CoreSettingsLdapIndexRoute
  '/_esm/cases/$caseId/': typeof EsmCasesCaseIdIndexRoute
  '/_esm/cases/$caseId/edit/': typeof EsmCasesCaseIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session-timeout'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/departments/$departmentId'
    | '/departments/create'
    | '/groups/$groupId'
    | '/groups/create'
    | '/roles/$roleId'
    | '/roles/create'
    | '/sla/$slaId'
    | '/sla/create'
    | '/users/$userId'
    | '/users/create'
    | '/cases/create'
    | '/login/'
    | '/categories/'
    | '/dashboard/'
    | '/departments/'
    | '/groups/'
    | '/permissions/'
    | '/roles/'
    | '/settings/'
    | '/sla/'
    | '/users/'
    | '/cases/'
    | '/settings/ldap/'
    | '/cases/$caseId/'
    | '/cases/$caseId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/session-timeout'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/departments/$departmentId'
    | '/departments/create'
    | '/groups/$groupId'
    | '/groups/create'
    | '/roles/$roleId'
    | '/roles/create'
    | '/sla/$slaId'
    | '/sla/create'
    | '/users/$userId'
    | '/users/create'
    | '/cases/create'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/departments'
    | '/groups'
    | '/permissions'
    | '/roles'
    | '/settings'
    | '/sla'
    | '/users'
    | '/cases'
    | '/settings/ldap'
    | '/cases/$caseId'
    | '/cases/$caseId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_core'
    | '/_esm'
    | '/session-timeout'
    | '/_core/categories/$categoryId'
    | '/_core/categories/create'
    | '/_core/departments/$departmentId'
    | '/_core/departments/create'
    | '/_core/groups/$groupId'
    | '/_core/groups/create'
    | '/_core/roles/$roleId'
    | '/_core/roles/create'
    | '/_core/sla/$slaId'
    | '/_core/sla/create'
    | '/_core/users/$userId'
    | '/_core/users/create'
    | '/_esm/cases/create'
    | '/_auth/login/'
    | '/_core/categories/'
    | '/_core/dashboard/'
    | '/_core/departments/'
    | '/_core/groups/'
    | '/_core/permissions/'
    | '/_core/roles/'
    | '/_core/settings/'
    | '/_core/sla/'
    | '/_core/users/'
    | '/_esm/cases/'
    | '/_core/settings/ldap/'
    | '/_esm/cases/$caseId/'
    | '/_esm/cases/$caseId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CoreRouteRoute: typeof CoreRouteRouteWithChildren
  EsmRouteRoute: typeof EsmRouteRouteWithChildren
  SessionTimeoutRoute: typeof SessionTimeoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session-timeout': {
      id: '/session-timeout'
      path: '/session-timeout'
      fullPath: '/session-timeout'
      preLoaderRoute: typeof SessionTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_esm': {
      id: '/_esm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EsmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core': {
      id: '/_core'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_esm/cases/': {
      id: '/_esm/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof EsmCasesIndexRouteImport
      parentRoute: typeof EsmRouteRoute
    }
    '/_core/users/': {
      id: '/_core/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof CoreUsersIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/sla/': {
      id: '/_core/sla/'
      path: '/sla'
      fullPath: '/sla/'
      preLoaderRoute: typeof CoreSlaIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/settings/': {
      id: '/_core/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof CoreSettingsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/roles/': {
      id: '/_core/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof CoreRolesIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/permissions/': {
      id: '/_core/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof CorePermissionsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/groups/': {
      id: '/_core/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof CoreGroupsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/departments/': {
      id: '/_core/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof CoreDepartmentsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/dashboard/': {
      id: '/_core/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof CoreDashboardIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/categories/': {
      id: '/_core/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CoreCategoriesIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_esm/cases/create': {
      id: '/_esm/cases/create'
      path: '/cases/create'
      fullPath: '/cases/create'
      preLoaderRoute: typeof EsmCasesCreateRouteImport
      parentRoute: typeof EsmRouteRoute
    }
    '/_core/users/create': {
      id: '/_core/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof CoreUsersCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/users/$userId': {
      id: '/_core/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof CoreUsersUserIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/sla/create': {
      id: '/_core/sla/create'
      path: '/sla/create'
      fullPath: '/sla/create'
      preLoaderRoute: typeof CoreSlaCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/sla/$slaId': {
      id: '/_core/sla/$slaId'
      path: '/sla/$slaId'
      fullPath: '/sla/$slaId'
      preLoaderRoute: typeof CoreSlaSlaIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/roles/create': {
      id: '/_core/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof CoreRolesCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/roles/$roleId': {
      id: '/_core/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof CoreRolesRoleIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/groups/create': {
      id: '/_core/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof CoreGroupsCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/groups/$groupId': {
      id: '/_core/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof CoreGroupsGroupIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/departments/create': {
      id: '/_core/departments/create'
      path: '/departments/create'
      fullPath: '/departments/create'
      preLoaderRoute: typeof CoreDepartmentsCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/departments/$departmentId': {
      id: '/_core/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof CoreDepartmentsDepartmentIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/categories/create': {
      id: '/_core/categories/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof CoreCategoriesCreateRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/categories/$categoryId': {
      id: '/_core/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CoreCategoriesCategoryIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_esm/cases/$caseId/': {
      id: '/_esm/cases/$caseId/'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof EsmCasesCaseIdIndexRouteImport
      parentRoute: typeof EsmRouteRoute
    }
    '/_core/settings/ldap/': {
      id: '/_core/settings/ldap/'
      path: '/settings/ldap'
      fullPath: '/settings/ldap/'
      preLoaderRoute: typeof CoreSettingsLdapIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_esm/cases/$caseId/edit/': {
      id: '/_esm/cases/$caseId/edit/'
      path: '/cases/$caseId/edit'
      fullPath: '/cases/$caseId/edit/'
      preLoaderRoute: typeof EsmCasesCaseIdEditIndexRouteImport
      parentRoute: typeof EsmRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CoreRouteRouteChildren {
  CoreCategoriesCategoryIdRoute: typeof CoreCategoriesCategoryIdRoute
  CoreCategoriesCreateRoute: typeof CoreCategoriesCreateRoute
  CoreDepartmentsDepartmentIdRoute: typeof CoreDepartmentsDepartmentIdRoute
  CoreDepartmentsCreateRoute: typeof CoreDepartmentsCreateRoute
  CoreGroupsGroupIdRoute: typeof CoreGroupsGroupIdRoute
  CoreGroupsCreateRoute: typeof CoreGroupsCreateRoute
  CoreRolesRoleIdRoute: typeof CoreRolesRoleIdRoute
  CoreRolesCreateRoute: typeof CoreRolesCreateRoute
  CoreSlaSlaIdRoute: typeof CoreSlaSlaIdRoute
  CoreSlaCreateRoute: typeof CoreSlaCreateRoute
  CoreUsersUserIdRoute: typeof CoreUsersUserIdRoute
  CoreUsersCreateRoute: typeof CoreUsersCreateRoute
  CoreCategoriesIndexRoute: typeof CoreCategoriesIndexRoute
  CoreDashboardIndexRoute: typeof CoreDashboardIndexRoute
  CoreDepartmentsIndexRoute: typeof CoreDepartmentsIndexRoute
  CoreGroupsIndexRoute: typeof CoreGroupsIndexRoute
  CorePermissionsIndexRoute: typeof CorePermissionsIndexRoute
  CoreRolesIndexRoute: typeof CoreRolesIndexRoute
  CoreSettingsIndexRoute: typeof CoreSettingsIndexRoute
  CoreSlaIndexRoute: typeof CoreSlaIndexRoute
  CoreUsersIndexRoute: typeof CoreUsersIndexRoute
  CoreSettingsLdapIndexRoute: typeof CoreSettingsLdapIndexRoute
}

const CoreRouteRouteChildren: CoreRouteRouteChildren = {
  CoreCategoriesCategoryIdRoute: CoreCategoriesCategoryIdRoute,
  CoreCategoriesCreateRoute: CoreCategoriesCreateRoute,
  CoreDepartmentsDepartmentIdRoute: CoreDepartmentsDepartmentIdRoute,
  CoreDepartmentsCreateRoute: CoreDepartmentsCreateRoute,
  CoreGroupsGroupIdRoute: CoreGroupsGroupIdRoute,
  CoreGroupsCreateRoute: CoreGroupsCreateRoute,
  CoreRolesRoleIdRoute: CoreRolesRoleIdRoute,
  CoreRolesCreateRoute: CoreRolesCreateRoute,
  CoreSlaSlaIdRoute: CoreSlaSlaIdRoute,
  CoreSlaCreateRoute: CoreSlaCreateRoute,
  CoreUsersUserIdRoute: CoreUsersUserIdRoute,
  CoreUsersCreateRoute: CoreUsersCreateRoute,
  CoreCategoriesIndexRoute: CoreCategoriesIndexRoute,
  CoreDashboardIndexRoute: CoreDashboardIndexRoute,
  CoreDepartmentsIndexRoute: CoreDepartmentsIndexRoute,
  CoreGroupsIndexRoute: CoreGroupsIndexRoute,
  CorePermissionsIndexRoute: CorePermissionsIndexRoute,
  CoreRolesIndexRoute: CoreRolesIndexRoute,
  CoreSettingsIndexRoute: CoreSettingsIndexRoute,
  CoreSlaIndexRoute: CoreSlaIndexRoute,
  CoreUsersIndexRoute: CoreUsersIndexRoute,
  CoreSettingsLdapIndexRoute: CoreSettingsLdapIndexRoute,
}

const CoreRouteRouteWithChildren = CoreRouteRoute._addFileChildren(
  CoreRouteRouteChildren,
)

interface EsmRouteRouteChildren {
  EsmCasesCreateRoute: typeof EsmCasesCreateRoute
  EsmCasesIndexRoute: typeof EsmCasesIndexRoute
  EsmCasesCaseIdIndexRoute: typeof EsmCasesCaseIdIndexRoute
  EsmCasesCaseIdEditIndexRoute: typeof EsmCasesCaseIdEditIndexRoute
}

const EsmRouteRouteChildren: EsmRouteRouteChildren = {
  EsmCasesCreateRoute: EsmCasesCreateRoute,
  EsmCasesIndexRoute: EsmCasesIndexRoute,
  EsmCasesCaseIdIndexRoute: EsmCasesCaseIdIndexRoute,
  EsmCasesCaseIdEditIndexRoute: EsmCasesCaseIdEditIndexRoute,
}

const EsmRouteRouteWithChildren = EsmRouteRoute._addFileChildren(
  EsmRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CoreRouteRoute: CoreRouteRouteWithChildren,
  EsmRouteRoute: EsmRouteRouteWithChildren,
  SessionTimeoutRoute: SessionTimeoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
